# stolen from github.com/mr-karan/hydra

- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Install dependencies
  apt:
      name: "{{ packages }}"
  vars:
      packages:
        - apt-transport-https
        - neovim
        - git
        - python3-pip
        - curl
        - aria2
        - ufw

- name: install unattended-upgrades
  apt:
    name: "unattended-upgrades"
    state: present

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
